CREATE TABLE test_tbl (
  `id` int(3) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `string` varchar(256) NOT NULL DEFAULT 'test string',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)